"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
[](fg:teal bg:bright-blue)\
$directory\
[](fg:bright-blue bg:muted-blue)\
$git_branch\
$git_status\
[](fg:muted-blue bg:dark-blue)\
$python\
$nodejs\
$rust\
$golang\
$php\
$time\
[](fg:dark-blue)\
\n$character"""

palette = 'my_color'

[os]
disabled = false
style = "bg:teal fg:black"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:bright-blue fg:white"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:muted-blue"
format = '[[ $symbol $branch ](bg:muted-blue fg:white)]($style)'

[git_status]
style = "bg:muted-blue"
format = '[[($all_status$ahead_behind)](fg:white bg:muted-blue)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:bright-blue bg:green)]($style)'

[c]
symbol = " "
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[rust]
symbol = ""
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[golang]
symbol = ""
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[php]
symbol = ""
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[java]
symbol = " "
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[kotlin]
symbol = ""
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[haskell]
symbol = ""
style = "bg:dark-blue"
format = '[[ $symbol( $version) ](fg:bright-blue bg:dark-blue)]($style)'

[python]
symbol = ""
style = "bg:dark-blue"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:bright-blue bg:dark-blue)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:bright-blue bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:bright-blue bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = true
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = true
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = true
show_notifications = true
min_time_to_notify = 45000

[palettes.my_color]
black = "#090c0c"
white = "#e3e5e5"
dark-navy = "#1d2230"
dark-blue = "#212736"
muted-blue = "#394260"
bright-blue = "#769ff0"
teal = "#a3aed2"
